version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: .github/workflows
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - "*"
