import { sidebar } from "vuepress-theme-hope";

export default sidebar([
  "/",
  "/contact/",
  {
    link: "/enrollment/",
    text: "😍 初入肥宣",
    children: [
      "/enrollment/intro",
      "/enrollment/card",
      "/enrollment/transport",
      "/enrollment/preparation",
      "/enrollment/books",
      "/enrollment/military_training",
      "/enrollment/city_center",
    ],
    collapsible: true,
  },
  {
    link: "/campus/",
    text: "🦢 校园",
    children: [
      "/campus/library",
      "/campus/colleges",
      "/campus/activity_center",
      "/campus/gym",
      "/campus/playground",
      "/campus/dorm",
      {
        text: "食堂&评测",
        link: "/campus/cafeterias",
        children: ["/campus/cafeteria_north", "/campus/cafeteria_south"],
      },
      "/campus/lost_and_found",
    ],
    collapsible: true,
  },
  {
    text: "💈 生活",
    children: [
      "/life/calendar",
      "/life/dormitory",
      "/life/alimony",
      "/life/transport",
      "/life/network",
      "/life/exercise",
      "/life/couriers",
      "/life/app",
      "/life/voluntarily",
      "/life/group",
    ],
    collapsible: true,
  },
  {
    text: "👨🏻‍🎓 学生组织",
    link: "/organizations/",
    children: [
      {
        text: "校级",
        children: [
          "/organizations/school/media_center",
          "/organizations/school/sports_team",
        ],
      },
      {
        text: "宣区校级",
        link: "/organizations/xuan/",
        children: [
          "/organizations/xuan/student_union",
          "/organizations/xuan/grassroots_organization_building_center",
          "/organizations/xuan/flag_guards",
          "/organizations/xuan/newx",
          "/organizations/xuan/association_management_service_center",
          "/organizations/xuan/youth_volunteer_federation",
          "/organizations/xuan/art_group",
          "/organizations/xuan/federation_for_innovation",
          "/organizations/xuan/center_for_academic_affairs",
          "/organizations/xuan/mental_health_association",
        ],
        collapsible: false,
      },
      "/organizations/faculties",
      "/organizations/associations",
    ],
    collapsible: true,
  },
  {
    text: "🎓 学习",
    children: [
      "/study/first",
      "/study/second",
      "/study/electives",
      "/study/change_major",
      "/study/exemption",
      "/study/CPC",
      "/study/lab",
      "/study/contest",
    ],
    collapsible: true,
  },
  "/surroundings/",
  "/xuan/",
  "/other/",
]);
