name: Ongoing Event Bot

on:
  issues:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  create-pr:
    if: github.event.label.name == 'ongoing-event'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: dev

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Parse issue form
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: .github/ISSUE_TEMPLATE/ongoing_event.yml

      - name: Update ongoing.json
        id: update-data
        env:
          INPUT_ISSUE_PARSER_JSON: ${{ steps.issue-parser.outputs.jsonString }}
        run: pnpm dlx tsx scripts/ongoing-event-bot.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ steps.update-data.outputs.commit-message }}
          title: ${{ steps.update-data.outputs.pr-title }}
          body: ${{ steps.update-data.outputs.pr-body }}
          branch: 'ongoing-event-${{ github.event.issue.number }}'
          base: 'dev'

      - name: React to issue
        uses: aidan-mundy/react-to-issue@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          reactions: rocket
